=== Asaf-prog/stepper/stepper_GUI/Content/Ex2/Stepper-V2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2008 rel. 2 (http://www.altova.com) by mazuki (darksiderg) -->
<!--W3C Schema generated by XMLSpy v2008 rel. 2 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="ST-StepsInFlow">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ST-StepInFlow" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ST-Stepper">
		<xs:complexType>
			<xs:all>
				<xs:element ref="ST-Flows"/>
				<xs:element name="ST-ThreadPool" type="xs:int"/>
			</xs:all>
		</xs:complexType>
	</xs:element>
	<xs:element name="ST-StepInFlow">
		<xs:complexType>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="alias" type="xs:string"/>
			<xs:attribute name="continue-if-failing" type="xs:boolean"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="ST-Flows">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ST-Flow" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ST-FlowOutput" type="xs:string"/>
	<xs:element name="ST-FlowLevelAliasing">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ST-FlowLevelAlias" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ST-FlowLevelAlias">
		<xs:complexType>
			<xs:attribute name="step" type="xs:string" use="required"/>
			<xs:attribute name="source-data-name" type="xs:string" use="required"/>
			<xs:attribute name="alias" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="ST-Flow">
		<xs:complexType>
			<xs:all>
				<xs:element ref="ST-FlowOutput"/>
				<xs:element ref="ST-CustomMappings" minOccurs="0"/>
				<xs:element ref="ST-FlowLevelAliasing" minOccurs="0"/>
				<xs:element ref="ST-Continuations" minOccurs="0"/>
				<xs:element ref="ST-InitialInputValues" minOccurs="0"/>
				<xs:element ref="ST-StepsInFlow"/>
				<xs:element name="ST-FlowDescription" type="xs:string"/>
			</xs:all>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="ST-CustomMappings">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ST-CustomMapping" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ST-CustomMapping">
		<xs:complexType>
			<xs:attribute name="target-step" type="xs:string" use="required"/>
			<xs:attribute name="target-data" type="xs:string" use="required"/>
			<xs:attribute name="source-step" type="xs:string" use="required"/>
			<xs:attribute name="source-data" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="ST-Continuations">
		<xs:complexType>
			<xs:sequence maxOccurs="unbounded">
				<xs:element ref="ST-Continuation"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ST-Continuation-Mapping">
		<xs:complexType>
			<xs:attribute name="target-data" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="TIME_TO_SPEND"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="source-data" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="ST-Continuation">
		<xs:complexType>
			<xs:sequence maxOccurs="unbounded">
				<xs:element ref="ST-Continuation-Mapping" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="target-flow" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="ST-InitialInputValues">
		<xs:complexType>
			<xs:sequence maxOccurs="unbounded">
				<xs:element ref="ST-InitialInputValue"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ST-InitialInputValue">
		<xs:complexType>
			<xs:attribute name="input-name" type="xs:string" use="required"/>
			<xs:attribute name="initial-value" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Asaf-prog/stepper/data/Ex2/xml/ex-amit2.xml
<?xml version="1.0" encoding="UTF-8"?>
<ST-Stepper xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Stepper-V2.xsd">
	<ST-ThreadPool>6</ST-ThreadPool>
	<ST-Flows>
		<ST-Flow name="Rename Files Zip Results">
			<ST-FlowDescription>Given a folder adds prefix and\or suffix to each file name.</ST-FlowDescription>		
			<ST-FlowOutput>TOTAL_FOUND</ST-FlowOutput>
			<ST-StepsInFlow>
				<ST-StepInFlow name="Collect Files In Folder"/>
			</ST-StepsInFlow>
			<ST-Continuations>
				<ST-Continuation target-flow="Delete Matched Files">
					<ST-Continuation-Mapping source-data="TOTAL_FOUND" target-data="TIME_TO_SPEND"/>
				</ST-Continuation>
			</ST-Continuations>
		</ST-Flow>
		<ST-Flow name="Delete Matched Files">
			<ST-FlowDescription>Given a folder, deletes files matching a certain pattern</ST-FlowDescription>		
			<ST-FlowOutput>TOTAL_FOUND,DELETION_STATS</ST-FlowOutput>
			<ST-StepsInFlow>
				<ST-StepInFlow name="Collect Files In Folder"/>
				<ST-StepInFlow name="Spend Some Time"/>
				<ST-StepInFlow name="Files Deleter"/>
			</ST-StepsInFlow>
		</ST-Flow>
	</ST-Flows>
</ST-Stepper>

=== Asaf-prog/stepper/data/Ex2/xml/workingXml/ex2.xml
<?xml version="1.0" encoding="UTF-8"?>
<ST-Stepper xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Stepper-V2.xsd">
	<ST-ThreadPool>6</ST-ThreadPool>
	<ST-Flows>
		<ST-Flow name="Rename Files Zip Results">
			<ST-FlowDescription>Given a folder adds prefix and\or suffix to each file name. The renaming results are expressed via CSV and Properties files and are finally zipped</ST-FlowDescription>		
			<ST-FlowOutput>PROP_RESULT,CSV_RESULT</ST-FlowOutput>
			<ST-StepsInFlow>
				<ST-StepInFlow name="Collect Files In Folder"/>
				<ST-StepInFlow name="Files Renamer"/>
				<ST-StepInFlow name="CSV Exporter"/>
				<ST-StepInFlow name="File Dumper" alias="CSV File Dumper"/>
				<ST-StepInFlow name="Zipper" alias="ZIP CSV File" continue-if-failing="true"/>
				<ST-StepInFlow name="Properties Exporter"/>
				<ST-StepInFlow name="File Dumper" alias="Properties File Dumper"/>
				<ST-StepInFlow name="Zipper" alias="ZIP Prop File" continue-if-failing="true"/>
			</ST-StepsInFlow>
			<ST-FlowLevelAliasing>
				<ST-FlowLevelAlias step="Files Renamer" source-data-name="RENAME_RESULT" alias="SOURCE"/>
				<ST-FlowLevelAlias step="CSV File Dumper" source-data-name="FILE_NAME" alias="CSV_FILE_NAME"/>
				<ST-FlowLevelAlias step="CSV File Dumper" source-data-name="RESULT" alias="CSV_FILE_DUMP_RESULT"/>								
				<ST-FlowLevelAlias step="CSV Exporter" source-data-name="RESULT" alias="CSV_RESULT"/>
				<ST-FlowLevelAlias step="Properties File Dumper" source-data-name="FILE_NAME" alias="PROP_FILE_NAME"/>
				<ST-FlowLevelAlias step="Properties File Dumper" source-data-name="RESULT" alias="PROP_FILE_DUMP_RESULT"/>
				<ST-FlowLevelAlias step="Properties Exporter" source-data-name="RESULT" alias="PROP_RESULT"/>
				<ST-FlowLevelAlias step="ZIP CSV File" source-data-name="SOURCE" alias="CSV_FILE_NAME"/>
				<ST-FlowLevelAlias step="ZIP CSV File" source-data-name="RESULT" alias="CSV_ZIP_RESULT"/>
				<ST-FlowLevelAlias step="ZIP Prop File" source-data-name="SOURCE" alias="PROP_FILE_NAME"/>				
				<ST-FlowLevelAlias step="ZIP Prop File" source-data-name="RESULT" alias="PROP_ZIP_RESULT"/>				
			</ST-FlowLevelAliasing>
			<ST-CustomMappings>
				<ST-CustomMapping source-step="Collect Files In Folder" source-data="FILES_LIST" target-step="Files Renamer" target-data="FILES_TO_RENAME"/>
				<ST-CustomMapping source-step="CSV Exporter" source-data="CSV_RESULT" target-step="CSV File Dumper" target-data="CONTENT"/>
				<ST-CustomMapping source-step="Properties Exporter" source-data="PROP_RESULT" target-step="Properties File Dumper" target-data="CONTENT"/>
			</ST-CustomMappings>
			<ST-Continuations>
				<ST-Continuation target-flow="Delete Matched Files">
					<ST-Continuation-Mapping source-data="TOTAL_FOUND" target-data="TIME_TO_SPEND"/>
				</ST-Continuation>
			</ST-Continuations>
			<ST-InitialInputValues>
				<ST-InitialInputValue input-name="OPERATION" initial-value="ZIP"/>
			</ST-InitialInputValues>			
		</ST-Flow>
		<ST-Flow name="Delete Matched Files">
			<ST-FlowDescription>Given a folder, deletes files matching a certain pattern</ST-FlowDescription>		
			<ST-FlowOutput>TOTAL_FOUND,DELETION_STATS</ST-FlowOutput>
			<ST-StepsInFlow>
				<ST-StepInFlow name="Collect Files In Folder"/>
				<ST-StepInFlow name="Spend Some Time"/>
				<ST-StepInFlow name="Files Deleter"/>
			</ST-StepsInFlow>
		</ST-Flow>
		<ST-Flow name="Store Command Result">
			<ST-FlowDescription>Invoke a command line and plots its output to a file. The file is then zipped</ST-FlowDescription>				
			<ST-FlowOutput>CONTENT</ST-FlowOutput>
			<ST-StepsInFlow>
				<ST-StepInFlow name="Command Line"/>
				<ST-StepInFlow name="File Dumper"/>
				<ST-StepInFlow name="Zipper"/>
			</ST-StepsInFlow>
			<ST-FlowLevelAliasing>
				<ST-FlowLevelAlias step="Command Line" source-data-name="RESULT" alias="CONTENT"/>
				<ST-FlowLevelAlias step="Zipper" source-data-name="SOURCE" alias="FILE_NAME"/>
				<ST-FlowLevelAlias step="Zipper" source-data-name="RESULT" alias="ZIP_RESULT"/>
			</ST-FlowLevelAliasing>
			<ST-InitialInputValues>
				<ST-InitialInputValue input-name="OPERATION" initial-value="ZIP"/>
			</ST-InitialInputValues>
		</ST-Flow>
	</ST-Flows>
</ST-Stepper>

=== Asaf-prog/stepper/data/Ex2/xml/workingXml/ex3-1.xml
<?xml version="1.0" encoding="UTF-8"?>
<ST-Stepper xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Stepper-V2.xsd">
	<ST-ThreadPool>2</ST-ThreadPool>
	<ST-Flows>
		<ST-Flow name="Rename Files Zip Results">
			<ST-FlowDescription>Given a folder adds prefix and\or suffix to each file name. The renaming results are expressed via CSV and Properties files and are finally zipped</ST-FlowDescription>	
			<ST-FlowOutput>PROP_RESULT,CSV_RESULT</ST-FlowOutput>
			<ST-StepsInFlow>
				<ST-StepInFlow name="Collect Files In Folder"/>
				<ST-StepInFlow name="Files Renamer"/>
				<ST-StepInFlow name="CSV Exporter"/>
				<ST-StepInFlow name="File Dumper" alias="CSV File Dumper"/>
				<ST-StepInFlow name="Zipper" alias="ZIP CSV File" continue-if-failing="true"/>
				<ST-StepInFlow name="Properties Exporter"/>
				<ST-StepInFlow name="File Dumper" alias="Properties File Dumper"/>
				<ST-StepInFlow name="Zipper" alias="ZIP Prop File" continue-if-failing="true"/>
			</ST-StepsInFlow>
			<ST-FlowLevelAliasing>
				<ST-FlowLevelAlias step="Files Renamer" source-data-name="RENAME_RESULT" alias="SOURCE"/>
				<ST-FlowLevelAlias step="CSV File Dumper" source-data-name="FILE_NAME" alias="CSV_FILE_NAME"/>
				<ST-FlowLevelAlias step="CSV File Dumper" source-data-name="RESULT" alias="CSV_FILE_DUMP_RESULT"/>								
				<ST-FlowLevelAlias step="CSV Exporter" source-data-name="RESULT" alias="CSV_RESULT"/>
				<ST-FlowLevelAlias step="Properties File Dumper" source-data-name="FILE_NAME" alias="PROP_FILE_NAME"/>
				<ST-FlowLevelAlias step="Properties File Dumper" source-data-name="RESULT" alias="PROP_FILE_DUMP_RESULT"/>
				<ST-FlowLevelAlias step="Properties Exporter" source-data-name="RESULT" alias="PROP_RESULT"/>
				<ST-FlowLevelAlias step="ZIP CSV File" source-data-name="SOURCE" alias="CSV_FILE_NAME"/>
				<ST-FlowLevelAlias step="ZIP CSV File" source-data-name="RESULT" alias="CSV_ZIP_RESULT"/>
				<ST-FlowLevelAlias step="ZIP Prop File" source-data-name="SOURCE" alias="PROP_FILE_NAME"/>				
				<ST-FlowLevelAlias step="ZIP Prop File" source-data-name="RESULT" alias="PROP_ZIP_RESULT"/>					
			</ST-FlowLevelAliasing>
			<ST-CustomMappings>
				<ST-CustomMapping source-step="Collect Files In Folder" source-data="FILES_LIST" target-step="Files Renamer" target-data="FILES_TO_RENAME"/>
				<ST-CustomMapping source-step="CSV Exporter" source-data="CSV_RESULT" target-step="CSV File Dumper" target-data="CONTENT"/>
				<ST-CustomMapping source-step="Properties Exporter" source-data="PROP_RESULT" target-step="Properties File Dumper" target-data="CONTENT"/>
			</ST-CustomMappings>
			<ST-Continuations>
				<ST-Continuation target-flow="Delete Matched Files">
					<ST-Continuation-Mapping source-data="TOTAL_FOUND" target-data="TIME_TO_SPEND"/>
				</ST-Continuation>
			</ST-Continuations>
			<ST-InitialInputValues>
				<ST-InitialInputValue input-name="OPERATION" initial-value="ZIP"/>
			</ST-InitialInputValues>			
		</ST-Flow>
		<ST-Flow name="API Invocation">
			<ST-FlowDescription>Invokes and API call to a server. Fetch data from the expected json result and dump it to a file</ST-FlowDescription>	
			<ST-FlowOutput>CODE,RESULT</ST-FlowOutput>
			<ST-StepsInFlow>
				<ST-StepInFlow name="HTTP Call"/>
				<ST-StepInFlow name="To Json"/>
				<ST-StepInFlow name="Json Data Extractor"/>
				<ST-StepInFlow name="File Dumper"/>
			</ST-StepsInFlow>
			<ST-FlowLevelAliasing>
				<ST-FlowLevelAlias step="File Dumper" source-data-name="CONTENT" alias="FILE_CONTENT"/>
			</ST-FlowLevelAliasing>
			<ST-CustomMappings>
				<ST-CustomMapping source-step="HTTP Call" source-data="RESPONSE_BODY" target-step="To Json" target-data="CONTENT"/>
				<ST-CustomMapping source-step="Json Data Extractor" source-data="VALUE" target-step="File Dumper" target-data="FILE_CONTENT"/>
			</ST-CustomMappings>		
			<ST-InitialInputValues>
				<ST-InitialInputValue input-name="PROTOCOL" initial-value="https"/>
			</ST-InitialInputValues>			
		</ST-Flow>
	</ST-Flows>
</ST-Stepper>

=== Asaf-prog/stepper/data/Ex2/xml/workingXml/ex-amit2Cl.xml
<?xml version="1.0" encoding="UTF-8"?>
<ST-Stepper xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Stepper-V2.xsd">
	<ST-ThreadPool>6</ST-ThreadPool>
	<ST-Flows>
		<ST-Flow name="Rename Files Zip Results">
			<ST-FlowDescription>Given a folder adds prefix and\or suffix to each file name.</ST-FlowDescription>		
			<ST-FlowOutput>TOTAL_FOUND2</ST-FlowOutput>
			<ST-StepsInFlow>
				<ST-StepInFlow name="Collect Files In Folder"/>
			</ST-StepsInFlow>
			<ST-FlowLevelAliasing>
				<ST-FlowLevelAlias step="Collect Files In Folder" source-data-name="TOTAL_FOUND" alias="TOTAL_FOUND2"/>
			</ST-FlowLevelAliasing>
			<ST-Continuations>
				<ST-Continuation target-flow="Delete Matched Files">
				</ST-Continuation>
			</ST-Continuations>
						
		</ST-Flow>
		<ST-Flow name="Delete Matched Files">
			<ST-FlowDescription>Given a folder, deletes files matching a certain pattern</ST-FlowDescription>		
			<ST-FlowOutput>TOTAL_FOUND,DELETION_STATS</ST-FlowOutput>
			<ST-StepsInFlow>
				<ST-StepInFlow name="Collect Files In Folder"/>
				<ST-StepInFlow name="Spend Some Time"/>
				<ST-StepInFlow name="Files Deleter"/>
			</ST-StepsInFlow>
			<ST-FlowLevelAliasing>
				<ST-FlowLevelAlias step="Spend Some Time" source-data-name="TIME_TO_SPEND" alias="TOTAL_FOUND2"/>
			</ST-FlowLevelAliasing>
			<ST-InitialInputValues>
				<ST-InitialInputValue input-name="FOLDER_NAME" initial-value="C:\Users\asafr\OneDrive\מסמכים\GitHub\stepper\data\Ex2\try\deleter"/>
			</ST-InitialInputValues>
			<ST-Continuations>
				<ST-Continuation target-flow="Rename Files Zip Results">
				</ST-Continuation>
			</ST-Continuations>
		</ST-Flow>
	</ST-Flows>
</ST-Stepper>

=== Asaf-prog/stepper/data/Ex2/xml/workingXml/ex3-2.xml
<?xml version="1.0" encoding="UTF-8"?>
<ST-Stepper xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Stepper-V2.xsd">
	<ST-ThreadPool>2</ST-ThreadPool>
	<ST-Flows>
		<ST-Flow name="Delete Matched Files">
			<ST-FlowDescription>Given a folder, deletes files matching a certain pattern</ST-FlowDescription>				
			<ST-FlowOutput>TOTAL_FOUND,DELETION_STATS</ST-FlowOutput>
			<ST-StepsInFlow>
				<ST-StepInFlow name="Collect Files In Folder"/>
				<ST-StepInFlow name="Spend Some Time"/>
				<ST-StepInFlow name="Files Deleter"/>
			</ST-StepsInFlow>
		</ST-Flow>
		<ST-Flow name="Store Command Result">
			<ST-FlowDescription>Invoke a command line and plots its output to a file. The file is then zipped</ST-FlowDescription>						
			<ST-FlowOutput>CONTENT</ST-FlowOutput>
			<ST-StepsInFlow>
				<ST-StepInFlow name="Command Line"/>
				<ST-StepInFlow name="File Dumper"/>
				<ST-StepInFlow name="Zipper"/>
			</ST-StepsInFlow>
			<ST-FlowLevelAliasing>
				<ST-FlowLevelAlias step="Command Line" source-data-name="RESULT" alias="CONTENT"/>
				<ST-FlowLevelAlias step="Zipper" source-data-name="SOURCE" alias="FILE_NAME"/>
				<ST-FlowLevelAlias step="Zipper" source-data-name="RESULT" alias="ZIP_RESULT"/>
			</ST-FlowLevelAliasing>
			<ST-InitialInputValues>
				<ST-InitialInputValue input-name="OPERATION" initial-value="ZIP"/>
			</ST-InitialInputValues>
		</ST-Flow>
	</ST-Flows>
</ST-Stepper>
